CREATE TABLE IF NOT EXISTS IMDB (
	IMDB_ID BIGSERIAL NOT NULL PRIMARY KEY,
	RATING INT4 NOT NULL,
	VOTES INT4 NOT NULL
);

CREATE TABLE IF NOT EXISTS COUNTRY (
    MOVIE_ID INT8 NOT NULL PRIMARY KEY,
    COUNTRY_CODE VARCHAR(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMMENT (
    COMMENT_ID BIGSERIAL NOT NULL PRIMARY KEY,
    MOVIE_ID INT8 NOT NULL,
    USER_ID INT8 NOT NULL,
    COMMENT_TEXT TEXT NOT NULL ,
    COMMENT_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS MOVIE (
    MOVIE_ID BIGSERIAL NOT NULL PRIMARY KEY,
    MOVIE_NAME VARCHAR(255) NOT NULL,
    PLOT VARCHAR(255) UNIQUE NOT NULL,
    RUNTIME INT4 NOT NULL,
    IMDB_ID INT8 UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTIST (
    ARTIST_ID BIGSERIAL NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS 'user' (
    USER_ID INT8 PRIMARY KEY,
    FIRST_NAME VARCHAR(255) UNIQUE NOT NULL,
    LAST_NAME VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS ARTIST_MOVIE (
    ARTIST_ID INT8 NOT NULL PRIMARY KEY,
    MOVIE_ID INT8 NOT NULL PRIMARY KEY
);

ALTER TABLE ARTIST_MOVIE ADD CONSTRAINT fk_artist_movie_id
FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST (ARTIST_ID);

ALTER TABLE ARTIST_MOVIE ADD CONSTRAINT fk_movie_artist_id
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (MOVIE_ID);

ALTER TABLE COMMENT ADD CONSTRAINT fk_movie_id
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (MOVIE_ID);

ALTER TABLE COMMENT ADD CONSTRAINT fk_user_id
FOREIGN KEY (USER_ID) REFERENCES 'user' (USER_ID);

ALTER TABLE MOVIE ADD CONSTRAINT fk_imdb_id
FOREIGN KEY (IMDB_ID) REFERENCES IMDB (IMDB_ID);