spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      properties:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
